// document.firstElementChild.lastElementChild.lastElementChild.lastElementChild.innerHTML = "Angela";
document.querySelector('ul').lastElementChild.innerHTML = "howdy";
document.getElementsByTagName('li')[2].style.color = 'purple';
document.getElementsByTagName('li').length;
document.getElementsByClassName('btn');
document.getElementById('title').innerHTML = "BLOOP";
document.querySelector("li a").style.color = "red";
document.querySelector('button').style.backgroundColor = 'yellow';
// document.querySelector('button').classList.add("huge");
document.querySelector('button').classList.toggle("huge");